### ISSUE TITLE
[grimoirelab2sh] Change the parser to remove `Unknown` enrollments

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/sortinghat#104]
Actually, the grimoirelab format does not use `Unknown` enrollments. Some people thought that in order to find `Unknown` enrollments in the file, would be helpful.

Having this in the file and with the current `grimoirelab2sh` will enroll those people as `Unknown` organization, which is wrong. It should be handled in a way that, everytime an Unknown is received, is removed before generating the sh json file.

Example. Actual information in Grimoirelab format:
```yaml
- profile:
    name: Alberto Martín
  email:
    - alberto.martin@bitergia.com
  github:
    - albertinisg
```

Desired one:
```yaml
- profile:
    name: Alberto Martín
  enrollments:
    - organization: Unknown
  email:
    - alberto.martin@bitergia.com
  github:
    - albertinisg
```
