### ISSUE TITLE
[grimoirelab2sh]  'no-strict-matching'  unsupported by the parser 

### ISSUE THREAD

**Issue by zhquan** [grimoirelab/sortinghat#107]
When we run the script with the following identity:
```yaml
- profile:
    name: mininet
  enrollments:
    - organization: Unknown
  email:
    - onosdev1
    - mininet@mininet-vm.(none)
```
we get the following error:
`Error: invalid GrimoireLab yaml format. Invalid email address: onosdev1`

As sortinghat already supports this kind of addresses, we expect the same behavior with this parser
